### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by MOMANI1** [fcannizzaro/material-stepper#24]
I don't know how it happened  
`Shutting down VM
04-16 23:48:59.844 26071-26071/android.alcode.com.material E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: android.alcode.com.material, PID: 26071
                                                                             java.lang.NoSuchFieldError: No static field continueButton of type I in class Lcom/github/fcannizzaro/materialstepper/R$id; or its superclasses (declaration of 'com.github.fcannizzaro.materialstepper.R$id' appears in /data/data/android.alcode.com.material/files/instant-run/dex/slice-slice_7-classes.dex)
                                                                                 at com.github.fcannizzaro.materialstepper.style.TabStepper.onCreate(TabStepper.java:78)
                                                                                 at android.alcode.com.material.newpost.NewPostActivityStepper.onCreate(NewPostActivityStepper.java:32)
                                                                                 at android.app.Activity.performCreate(Activity.java:6237)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by MOMANI1** [comment]
http://stackoverflow.com/a/33037203/4251431
duplicate resource id

**Comment by fcannizzaro** [comment]
Using v 1.1.3 does it keep crashing?
