### ISSUE TITLE
onNext => view is not always available

### ISSUE THREAD

**Issue by MFlisar** [fcannizzaro/material-stepper#45]
In the `onNext` function, the views are not always available... I get an exception (rarely) like following:

	java.lang.NullPointerException: Attempt to read from field 'android.widget.Switch com.app.package.databinding.ViewStepSettingsBinding.swSwitch' on a null object reference
	at com.app.package.setup.StepSettings.onNext(StepSettings.java:67)
	at com.github.fcannizzaro.materialstepper.style.BaseNavigation.onClick(BaseNavigation.java:59)
	at android.view.View.performClick(View.java:4785)
	at android.view.View$PerformClick.run(View.java:19884)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

Do you know when this happens? And why?

My class looks like following:

	public class StepSettings extends AbstractStep
	{
		private ViewStepSettingsBinding mBinding= null;
		private int mPos = -1;
		private SetupStep mSetupStep = null;

		@Override
		public void onCreate(Bundle savedInstanceState)
		{
			mPos = getArguments().getInt("pos", 0);
			mSetupStep = SetupStep.getById(getArguments().getInt("setupStep", 0));

			super.onCreate(savedInstanceState);
		}

		@Override
		public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {

			mBinding = DataBindingUtil.inflate(inflater, R.layout.view_step_settings, container, false);
			mBinding.swSwitch.setChecked(true);
			return mBinding.getRoot();
		}

		@Override
		public String name() {
			return getString(mSetupStep.getTitle());
		}

		@Override
		public boolean isOptional() {
			return true;
		}

		@Override
		public void onStepVisible() {
		}

		@Override
		public void onNext() {

			// THIS CAN HEPPEN!!! Why???
			if (mBinding.swSwitch == null)
				return;

			if (mBinding.swSwitch.isChecked())
			{
				if (PermissionUtil.hasAccessibilityPermission())
				{
					MainApp.getPrefs().enableService(true);
					MainApp.getPrefs().keepScreenOn(true);
				}
				if (PermissionUtil.canDrawOverlay(getActivity()))
				{
					MainApp.getPrefs().enableFab(true);
					MainApp.getPrefs().enableBlack(true);
				}
				BusProvider.getInstance().post(new SetupStepperEvent(mSetupStep));
			}
		}

		@Override
		public void onPrevious() {
		}

		@Override
		public String optional() {
			return "";
		}

		@Override
		public boolean nextIf() {
			return mPos > 1;
		}

		@Override
		public String error() {
			return "";
		}
	}

**Comment by fcannizzaro** [comment]
Did you tried [setStateAdapter()](https://github.com/fcannizzaro/material-stepper#setstateadapter) ?

**Comment by MFlisar** [comment]
No. My setup stepper has 3 or 4 pages depending on the device, I don't need the state adapter...

**Comment by gregdev** [comment]
Hi @MFlisar, did you ever find a fix for this one? I'm getting the same thing randomly and it's driving me nuts.
